renamed: default_theme.yml -> theme.yml

diff --git a/.github/workflows/verify_default_theme.yml b/.github/workflows/verify_default_theme.yml
--- a/.github/workflows/verify_default_theme.yml
+++ b/.github/workflows/verify_default_theme.yml
@@ -10,13 +10,13 @@ jobs:
       - name: Check out repository
         uses: actions/checkout@v4
 
-      - name: Verify default_theme.yml
+      - name: Verify theme.yml
         run: |
-          [[ -L default_theme.yml ]] || { echo "ERROR: default_theme.yml should be a symlink -> themes/NCAR_primary.yml"; exit 1; }
-          [[ "$(readlink default_theme.yml)" == "themes/NCAR_primary.yml" ]] || { echo "ERROR: default_theme.yml should be a symlink -> themes/NCAR_primary.yml"; exit 1; }
+          [[ -L theme.yml ]]                                         || { echo "ERROR: theme.yml should be a symlink -> themes/NCAR_primary.yml"; exit 1; }
+          [[ "$(readlink theme.yml)" == "themes/NCAR_primary.yml" ]] || { echo "ERROR: theme.yml should be a symlink -> themes/NCAR_primary.yml"; exit 1; }
 
       - name: Verify docs/stylesheets/custom.css
         run: |
           cd docs/stylesheets/
-          [[ -L custom.css ]] || { echo "ERROR: custom.css should be a symlink -> NCAR_primary.css"; exit 1; }
+          [[ -L custom.css ]]                                  || { echo "ERROR: custom.css should be a symlink -> NCAR_primary.css"; exit 1; }
           [[ "$(readlink custom.css)" == "NCAR_primary.css" ]] || { echo "ERROR: custom.css should be a symlink -> NCAR_primary.css"; exit 1; }
