CI workflow to validate default environment symbolic links

diff --git a/.github/workflows/verify_default_theme.yml b/.github/workflows/verify_default_theme.yml
--- a/.github/workflows/verify_default_theme.yml
+++ b/.github/workflows/verify_default_theme.yml
@@ -12,9 +12,11 @@ jobs:
 
       - name: Verify default_theme.yml
         run: |
-          diff default_theme.yml themes/NCAR_primary.yml >/dev/null || { echo "ERROR: default_theme.yml should -> themes/NCAR_primary.yml"; exit 1; }
+          [[ -L default_theme.yml ]] || { echo "ERROR: default_theme.yml should -> themes/NCAR_primary.yml"; exit 1; }
+          [[ "$(readlink default_theme.yml)" == "themes/NCAR_primary.yml" ]] || { echo "ERROR: default_theme.yml should -> themes/NCAR_primary.yml"; exit 1; }
 
       - name: Verify docs/stylesheets/custom.css
         run: |
           cd docs/stylesheets/
-          diff custom.css NCAR_primary.css >/dev/null || { echo "ERROR: docs/stylesheets/custom.css should -> docs/stylesheets/NCAR_primary.css"; exit 1; }
+          [[ -L custom.css ]] || { echo "ERROR: custom.css should -> NCAR_primary.css"; exit 1; }
+          [[ "$(readlink custom.css)" == "NCAR_primary.css" ]] || { echo "ERROR: custom.css should -> NCAR_primary.css"; exit 1; }
